name: panvimdoc
on:
  push:
    paths:
      - .github/workflows/panvimdoc.yml
      - README.md
  workflow_dispatch:
permissions:
  contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    name: pandoc to vimdoc
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
      - name: Run panvimdoc for README
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types
          pandoc: README.md
          version: "NVIM >=v0.7.0"
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Auto-Commit
        uses: stefanzweifel/git-auto-commit-action@v7.2.0
        with:
          commit_message: "docs: auto generate docs"
          branch: ${{ github.head_ref }}
