name: panvimdoc plugins
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/panvimdoc_plugins.yml
      - docs/*.md
  workflow_dispatch:
permissions:
  contents: write
jobs:
  plugins:
    runs-on: ubuntu-latest
    name: pandoc to vimdoc (plugins)
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
      - name: Run panvimdoc for agent-deck.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-plugin.agent-deck
          description: "`agent-deck` types"
          pandoc: docs/agent-deck.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for ai-commander.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-plugin.ai-commander
          description: "`ai-commander` types"
          pandoc: docs/ai-commander.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for ai-helper.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-plugin.ai-helper
          description: "`ai-helper` types"
          pandoc: docs/ai-helper.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for attention.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-plugin.attention
          description: "`attention` types"
          pandoc: docs/attention.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for bar.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-plugin.bar
          description: "`bar` types"
          pandoc: docs/bar.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for battery.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-plugin.battery
          description: "`battery` types"
          pandoc: docs/battery.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for chord.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-plugin.chord
          description: "`chord` types"
          pandoc: docs/chord.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for cmd-sender.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-plugin.cmd-sender
          description: "`cmd-sender` types"
          pandoc: docs/cmd-sender.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for cmdpicker.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-plugin.cmdpicker
          description: "`cmdpicker` types"
          pandoc: docs/cmdpicker.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for dev.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-plugin.dev
          description: "`dev` types"
          pandoc: docs/dev.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for kanagawa.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-plugin.kanagawa
          description: "`kanagawa` types"
          pandoc: docs/kanagawa.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for lantern.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-plugin.lantern
          description: "`lantern` types"
          pandoc: docs/lantern.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for lib.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-plugin.lib
          description: "`lib` types"
          pandoc: docs/lib.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for listeners.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-plugin.listeners
          description: "`listeners` types"
          pandoc: docs/listeners.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for log.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-plugin.log
          description: "`log` types"
          pandoc: docs/log.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for memo.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-plugin.memo
          description: "`memo` types"
          pandoc: docs/memo.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for modal.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-plugin.modal
          description: "`modal` types"
          pandoc: docs/modal.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for passrelay.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-plugin.passrelay
          description: "`passrelay` types"
          pandoc: docs/passrelay.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for pinned-tabs.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-plugin.pinned-tabs
          description: "`pinned-tabs` types"
          pandoc: docs/pinned-tabs.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for pivot-panes.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-plugin.pivot-panes
          description: "`pivot-panes` types"
          pandoc: docs/pivot-panes.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for presentation.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-plugin.presentation
          description: "`presentation` types"
          pandoc: docs/presentation.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for quick-domains.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-plugin.quick-domains
          description: "`quick-domains` types"
          pandoc: docs/quick-domains.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for quickselect.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-plugin.quickselect
          description: "`quickselect` types"
          pandoc: docs/quickselect.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for quota-limit.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-plugin.quota-limit
          description: "`quota-limit` types"
          pandoc: docs/quota-limit.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for replay.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-plugin.replay
          description: "`replay` types"
          pandoc: docs/replay.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for resurrect.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-plugin.resurrect
          description: "`resurrect` types"
          pandoc: docs/resurrect.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for ribbon.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-plugin.ribbon
          description: "`ribbon` types"
          pandoc: docs/ribbon.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for rosepine.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-plugin.rosepine
          description: "`rosepine` types"
          pandoc: docs/rosepine.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for sessionizer.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-plugin.sessionizer
          description: "`sessionizer` types"
          pandoc: docs/sessionizer.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for sigil.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-plugin.sigil
          description: "`sigil` types"
          pandoc: docs/sigil.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for smart-splits.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-plugin.smart-splits
          description: "`smart-splits` types"
          pandoc: docs/smart-splits.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for smart-workspace-switcher.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-plugin.smart-workspace-switcher
          description: "`smart-workspace-switcher` types"
          pandoc: docs/smart-workspace-switcher.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for stack.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-plugin.stack
          description: "`stack` types"
          pandoc: docs/stack.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for sync.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-plugin.sync
          description: "`sync` types"
          pandoc: docs/sync.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for sync-panes.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-plugin.sync-panes
          description: "`sync-panes` types"
          pandoc: docs/sync-panes.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for tabline.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-plugin.tabline
          description: "`tabline` types"
          pandoc: docs/tabline.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for tabsets.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-plugin.tabsets
          description: "`tabsets` types"
          pandoc: docs/tabsets.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for toggle-terminal.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-plugin.toggle-terminal
          description: "`toggle-terminal` types"
          pandoc: docs/toggle-terminal.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for warp.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-plugin.warp
          description: "`warp` types"
          pandoc: docs/warp.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for wez-pain-control.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-plugin.wez-pain-control
          description: "`wez-pain-control` types"
          pandoc: docs/wez-pain-control.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for wez-tmux.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-plugin.wez-tmux
          description: "`wez-tmux` types"
          pandoc: docs/wez-tmux.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for wezterm-config.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-plugin.wezterm-config
          description: "`wezterm-config` types"
          pandoc: docs/wezterm-config.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for wezterm-sessions.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-plugin.wezterm-sessions
          description: "`wezterm-sessions` types"
          pandoc: docs/wezterm-sessions.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for wezterm-status.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-plugin.wezterm-status
          description: "`wezterm-status` types"
          pandoc: docs/wezterm-status.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for wezterm-tabs.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-plugin.wezterm-tabs
          description: "`wezterm-tabs` types"
          pandoc: docs/wezterm-tabs.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for wezterm-theme-rotator.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-plugin.wezterm-theme-rotator
          description: "`wezterm-theme-rotator` types"
          pandoc: docs/wezterm-theme-rotator.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for widgets.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-plugin.widgets
          description: "`widgets` types"
          pandoc: docs/widgets.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for workspace-picker.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-plugin.workspace-picker
          description: "`workspace-picker` types"
          pandoc: docs/workspace-picker.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for workspacesionizer.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-plugin.workspacesionizer
          description: "`workspacesionizer` types"
          pandoc: docs/workspacesionizer.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Run panvimdoc for wsinit.md
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: wezterm-types-plugin.wsinit
          description: "`wsinit` types"
          pandoc: docs/wsinit.md
          toc: false
          demojify: true
          dedupsubheadings: false
          treesitter: true
          ignorerawblocks: true
          docmapping: false
          docmappingprojectname: false
      - name: Auto-Commit
        uses: stefanzweifel/git-auto-commit-action@v7.2.0
        with:
          commit_message: "docs: auto generate docs"
          branch: ${{ github.head_ref }}
