name: Action Release
on:
  push:
    tags:
      - "v*.*.*"
  merge_group:
    branches:
      - main
  release:
    types:
      - created
permissions:
  contents: write
  discussions: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
      - name: Build Project Assets
        run: |
          mkdir -pv wezterm-types
          cp -rv assets lua doc docs README.md LICENSE .luarc.json Makefile wezterm-types
          tar cvJf wezterm-types.tar.xz wezterm-types
          tar cvzf wezterm-types.tar.gz wezterm-types
          zip -r -9 wezterm-types.zip wezterm-types
          7z a -mx9 -mmt -sdel wezterm-types.7z wezterm-types
          sha512sum wezterm-types.7z wezterm-types.zip wezterm-types.tar.gz wezterm-types.tar.xz >| sha512sums.txt
          md5sum wezterm-types.7z wezterm-types.zip wezterm-types.tar.gz wezterm-types.tar.xz >| md5sums.txt
      - name: Get Release
        uses: joutvhu/get-release@v1.0.4
        with:
          latest: true
          prerelease: true
          pattern: "^v.*"
          debug: true
          throwing: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Release File
        run: |
          echo ${{ github.sha }} > Release.txt
          cat Release.txt
      - name: Release
        uses: softprops/action-gh-release@v3.0.2
        if: github.ref_type == 'tag'
        with:
          files: |
            Release.txt
            md5sums.txt
            sha512sums.txt
            wezterm-types.7z
            wezterm-types.tar.gz
            wezterm-types.tar.xz
            wezterm-types.zip
          token: ${{ secrets.GITHUB_TOKEN }}
